### ISSUE TITLE
Peer to Peer Programming - Review

### ISSUE THREAD

**Issue by samlorlah** [uisendy/Leaderboard#4]
<img src="https://media2.giphy.com/media/QVgCZ7EsgfrB9GLcMa/giphy.gif"/>

You have done so well with this project

✔️ No Linters Error
✔️ Good use of github flow
✔️ Good use of Html, CSS and JavaScript practice

We congratulate you on a job well done.

**Comment by uisendy** [comment]
Thanks @samlorlah
